version: 2
jobs:
  build:
    working_directory: /go/src/github.com/mattermost/go-circleci
    environment:
      TEST_RESULTS: /tmp/test-results
    docker:
    - image: circleci/golang:1.16
    steps:
    - checkout
    - run: go vet ./...
    - run: go test ./...
